// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8ulJxXkPVWE4qf5ewhbO8On5FNABdFFY',
    appId: '1:185426472626:android:7c0acdc40f7cfc595a23ab',
    messagingSenderId: '185426472626',
    projectId: 'notesapp-codegenius',
    storageBucket: 'notesapp-codegenius.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7hh4cig35YmfYAec4yFNI-fTp5bc1DfI',
    appId: '1:185426472626:ios:b493ebedfb2eee5e5a23ab',
    messagingSenderId: '185426472626',
    projectId: 'notesapp-codegenius',
    storageBucket: 'notesapp-codegenius.appspot.com',
    iosClientId: '185426472626-sc1iv808tgmerg80fdhjjoiliopbf3k6.apps.googleusercontent.com',
    iosBundleId: 'com.codegenius.notesapp',
  );
}
